
### Login
# @name login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "user1",
    "password": "password"
}

###
@access_token = {{login.response.body.token}}

POST http://localhost:3000/cash
Content-Type: application/json
Authorization: Bearer {{access_token}}

### 

POST http://localhost:3000/cash/e82761e1-e50d-11ef-8564-0242ac110002
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

POST http://localhost:3000/cash/add
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "amount": 5000,
    "description": "New cashflow"
}

###

PUT http://localhost:3000/cash/update
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "cashflowId": "e82761e1-e50d-11ef-8564-0252ac110002",
    "amount": 150,
    "description": "Updated cashflow"
}

###

DELETE http://localhost:3000/cash/delete
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "cashflowId": "512c7eb8-f40b-11ef-a2b2-0242ac110002"
}